### ISSUE TITLE
Code example in 1.8

### ISSUE THREAD

**Issue by mathonsunday** [linkedin/swift-style-guide#10]
In 1.8 we have 

``` swift
func pancake() -> Pancake {
    /* ... */
}
```

This looks like a function that should either be a computed property if it has no side effects (we don't know since it's not implemented) or be prefixed with "make" according to the Swift API Guidelines.

Not a big deal, I can just see it being confusing.

**Comment by cezarywojcik** [comment]
I was actually thinking about this the other day, thanks for reminding me. Added `with syrup` inside of the function to make it more appropriate. I _do_ want to keep it as a function for the sake of the example.
