### ISSUE TITLE
Remove reference to VVDocumenter plugin 

### ISSUE THREAD

**Issue by mathonsunday** [linkedin/swift-style-guide#11]
From the README for VVDocumenter

> In Xcode 8, Apple integrated a comment documentation generator plugin, which is built on top of VVDocumenter...It means you could just use the shortcut (⌥ Option + ⌘ Command + /) to add a documentation comment to your code if you are using Xcode 8 or above!

Understand if you planning on changing this once Xcode 8 becomes more widely adopted.

**Comment by cezarywojcik** [comment]
That shortcut uses the `///` syntax instead of the block syntax, so it's not useful here. I'll remove the reference to VVDocumenter though since Apple sherlocked it into Xcode with no better alternative.
