### ISSUE TITLE
Add private init to singleton 

### ISSUE THREAD

**Issue by mathonsunday** [linkedin/swift-style-guide#9]
In 3.7.4., why don't we add 
`private init() {}`
to the suggested singleton declaration? This will makes sure that the compiler throws an error when any class attempts to initialize that singleton using the default `()` initializer. The approach is described in this [blog post](http://krakendev.io/blog/the-right-way-to-write-a-singleton). 

Happy to make a PR if this sounds like a good idea.

**Comment by plivesey** [comment]
I like this approach, but generally, don't think it's important enough to add a rule for. As in, if people want to include it great, but not a requirement.

Main reason is that I've never seen anyone screw this up before? But maybe other people have other experiences?

Actually, another thing is that I do do this for dependency injection in tests. So ultimately, this will need to be internal for testing which is the default anyway?

**Comment by plivesey** [comment]
Maybe I'm making a wrong assumption here though...here's my assumption:

`If a class has no public init, it cannot be subclassed.` <- is that true? I think so?

**Comment by mathonsunday** [comment]
I don't know if it's impossible, but it certainly would limit what you can do in the subclass. For example no calling super.init and it's not clear how overriding would be possible.

**Comment by plivesey** [comment]
Yeah, probably allowed to subclass but you can't create an instance because you can't create an init in the subclass (because you'd need to call super.init in that)

**Comment by cezarywojcik** [comment]
Just because something has a singleton doesn't mean it shouldn't be allowed to have other instances. For example, `UserDefaults.standard` is a singleton, but you can have other instances as well.

**Comment by mathonsunday** [comment]
@cezarywojcik Isn't that what we make singletons for? I have seen examples of creating a new type like ExtUserDefaults instead of using VoyagerUserDefaults. Do we currently create multiple instances of the same UserDefaults type?  

Either way, I wouldn't want to to through with this change based on Peter's comment on how this would affect dependency injection  in tests.

**Comment by cezarywojcik** [comment]
The `UserDefaults.standard` doesn't work across extensions, for example, which is why we need a separate instance of it initialized with a group ID that enables sharing the info between extensions and the app. The `.standard` singleton is appropriate for things only within an app. _Generally_, most singletons should be the only instance of a `class`, but there are legitimate use cases for a singleton to _not_ be the only possible instance.

**Comment by mathonsunday** [comment]
Makes sense, will close the issue.
